# 商品类目查询
from .jdUnionOpenCategoryGoodsGet import jdUnionOpenCategoryGoodsGet
# 优惠券领取情况查询接口
from .jdUnionOpenCouponQuery import jdUnionOpenCouponQuery
# 京粉精选商品查询接口
from .jdUnionOpenGoodsJingfenQuery import jdUnionOpenGoodsJingfenQuery
# 链接商品查询接口
from .jdUnionOpenGoodsLinkQuery import jdUnionOpenGoodsLinkQueryt
# 获取推广商品信息接口
from .jdUnionOpenGoodsPromotiongoodsinfoQuery import jdUnionOpenGoodsPromotiongoodsinfoQuery
# 关键词商品查询接口
from .jdUnionOpenGoodsQuery import jdUnionOpenGoodsQuery
# 秒杀商品查询接口
from .jdUnionOpenGoodsSeckillQuery import jdUnionOpenGoodsSeckillQuery
# 学生价商品查询接口
from .jdUnionOpenGoodsStupriceQuery import jdUnionOpenGoodsStupriceQuery
# 奖励订单查询接口
from .jdUnionOpenOrderBonusQuery import jdUnionOpenOrderBonusQuery
# 查询推广订单及佣金信息，会随着订单状态变化更新数据，支持按下单时间、完成时间或状态更新时间查询，
from .jdUnionOpenOrderQuery import jdUnionOpenOrderQuery
# 获取PID
from .jdUnionOpenUserPidGet import jdUnionOpenUserPidGet
# 通过unionId获取推广链接
from .jdUnionOpenPromotionByunionidGet import jdUnionOpenPromotionByunionidGet

from .jdUnionOpenoPromotionCommonGet import jdUnionOpenPromotionCommonGet

